version: '3.8'

services:
  # Node.js App Service
  app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  # PostgreSQL Database Service
  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Named volume for PostgreSQL data persistence
volumes:
  postgres_data: